---
host_packages:
  - linux
  - linux-lts
  - tailscale

host_gui_packages:
  - mesa-demos
  - nvidia-open-dkms
  - nvidia-utils

sddm_theme: sddm-astronaut-theme
sddm_astronaut_theme: pixel_sakura
wallpaper_image: john-towner-3Kv48NS4WUU-unsplash.jpg
